[project]
name = "jupyter-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bash-kernel>=0.10.0",
    "jupyterlab>=4.4.2",
    "kotlin-jupyter-kernel>=0.12.0.322",
    "ruff>=0.11.8",
]
